
GET http://localhost:3002/try-qs?name=andy&age=30

### 需用3個#字號分隔
POST http://localhost:3002/try-post
Content-Type: application/x-www-form-urlencoded

name=andy&age=55&data=abc

### 分隔線
POST http://localhost:3002/try-post
Content-Type: application/json

{
    "name": "andy",
    "data": "abc"
}

### 分隔線
GET http://tw.yahoo.com
